CRM_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from Organization.views import OrganizationViewSetAPI
from .views import homepage

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    # path('login/', loginpage, name="login"),
    # path('admin/logout', admin.site.urls, name="logout"),
    path('login/', auth_views.LoginView.as_view(template_name='login_page.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', homepage, name="homepage"),
    path('Organization/', include('Organization.urls')),
    path('Product/', include('Product.urls')),
    path('Quote/', include('Quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quote/urls.py
from django.urls import path
from .views import craete_quote,quote_list,send_email
app_name='Quote'
urlpatterns = [
    path('', craete_quote.as_view(), name='CreateQuote'),
    path('quotelist/', quote_list.as_view(), name='QuoteList'),
    path('sendemail/<int:pk>', send_email, name='SendEmail'),
]

auth/urls.py
from django.urls import path

urlpatterns = [

]

Quote/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Sum, F, Case, When
from django_jalali.db import models as jdate
from django.utils.translation import ugettext_lazy as _
# Create your models here.
from Organization.models import Organization
from Product.models import Product


class Quote(models.Model):
    user_creator = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name=_('کاربر ثبت کننده'))
    organ = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name=_('سازمان'))
    created_at = jdate.jDateTimeField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))
    tax = 9

    class Meta:
        verbose_name = _('پیش فاکتور')
        verbose_name_plural = _('پیش فاکتور ها')

    def __str__(self):
        return f'{self.organ}'

    def get_total_quantity(self):
        return self.quoteitem_set.all().aggregate(Sum('quantity')).get('quantity__sum', 0)

    def get_total_base_price(self):
        return self.quoteitem_set.all().annotate(total_base_price=F('quantity') * F('price')) \
            .aggregate(Sum('total_base_price'))['total_base_price__sum']

    def get_quote_discount(self):
        return self.quoteitem_set.all().annotate(
            total_base_price=F('quantity') * F('price')).annotate(
            total_discount=(F('discount') * F('total_base_price') / 100)) \
            .aggregate(Sum('total_discount'))['total_discount__sum']

    def get_quote_tax(self, tax=tax):
        return self.quoteitem_set.all().annotate(
            total_base_price=F('quantity') * F('price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_tax=Case(
                When(product__is_tax=True, then=(F('total_price') * tax / 100)),
                When(product__is_tax=False, then=0),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_tax'))['total_tax__sum']

    def get_total_price(self, tax=tax):
        return self.quoteitem_set.all().annotate(
            total_base_price=F('quantity') * F('price')).annotate(
            total_price=F('total_base_price') - (F('discount') * F('total_base_price') / 100)).annotate(
            total_price=Case(
                When(product__is_tax=True, then=F('total_price') + (F('total_price') * tax / 100)),
                When(product__is_tax=False, then=F('total_price')),
                output_field=models.PositiveIntegerField()
            )
        ).aggregate(Sum('total_price'))['total_price__sum']


class QuoteItem(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE, verbose_name=_('پیش فاکتور'))
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name=_('محصول'))
    price = models.PositiveIntegerField(default=0, verbose_name=_('قیمت'))
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)], verbose_name=_('تعداد'))
    discount = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)], verbose_name=_('درصد تخفیف'))

    class Meta:
        verbose_name = _('رکورد پیش فاکتور')
        verbose_name_plural = _('رکورد پیش فاکتورها')

    def __str__(self):
        return f'{self.quote} {self.product}'

    def get_total_price(self):
        return self.quantity * self.price


class EmailHistory(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE, verbose_name=_('پیش فاکتور'))
    description = models.TextField(verbose_name=_('متن ایمیل'))
    status = models.BooleanField(verbose_name=_('وضعیت ارسال'))
    email = models.EmailField(verbose_name=_("ایمیل مخاطب"), blank=True, )
    user_creator = models.ForeignKey(get_user_model(), on_delete=models.PROTECT,
                                     verbose_name=_('کاربر ثبت کننده'))
    created_at = jdate.jDateTimeField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))

    class Meta:
        verbose_name = _('تاریخچه ایمیل')
        verbose_name_plural = _('تاریخچه ایمیل ها')

Quote/forms.py
from . import models
from django.forms import modelformset_factory

QuoteItemCreateFormSet = modelformset_factory(models.QuoteItem, fields=('product', 'price', 'quantity', 'discount'),
                                              extra=1)

Quote/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.core import mail
# Create your views here.
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, ListView

from Organization.models import Organization
from .forms import QuoteItemCreateFormSet
from .models import QuoteItem, Quote, EmailHistory


class craete_quote(LoginRequiredMixin, CreateView):
    template_name = "CreateQuote.html"

    def get_context_data(self, **kwargs):
        formset = QuoteItemCreateFormSet(queryset=QuoteItem.objects.none())
        organizations = Organization.objects.filter(user_creator=self.request.user)
        return {'formset': formset, 'organizations': organizations}

    def post(self, *args, **kwargs):
        formset = QuoteItemCreateFormSet(data=self.request.POST)
        if formset.is_valid():
            organization = get_object_or_404(Organization, pk=self.request.POST['organization'],
                                             user_creator=self.request.user)
            quote = Quote.objects.create(user_creator=self.request.user, organ=organization)
            for form in formset:
                form.instance.quote = quote
                form.save()
            messages.success(self.request, "ثبت شد")
            return redirect(reverse_lazy("Quote:QuoteList"))


class quote_list(LoginRequiredMixin, ListView):
    model = Quote
    template_name = 'QuoteList.html'
    paginate_by = 4


@require_http_methods(["GET"])
@login_required
def send_email(request, pk):

    quote = get_object_or_404(Quote, pk=pk, user_creator=request.user)
    text = render_to_string('quotetext.txt', {'object': quote})
    email = quote.organ.email_owner
    sender = request.user.email
    emails = (
        ('Hey Man', text, sender, [email, ]),
    )
    try:
        results = mail.send_mass_mail(emails)
        p = EmailHistory(quote=quote,description=text,status=results,email=email,user_creator=request.user)
        p.save()
        messages.success(request, 'ایمیل با موفقیت ارسال شد.')
        return redirect(reverse_lazy('Quote:QuoteList'))
    except:
        p = EmailHistory(quote=quote, description=text, status=0, email=email, user_creator=request.user)
        p.save()
        messages.error(request, 'ارسال ایمیل انجام نشد.')
        return redirect(reverse_lazy('Quote:QuoteList'))

Quote/templates/CreateQuote.html
{% extends 'base/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Create Quote
{% endblock %}

{% block content %}
    <form id="form-container" method="POST">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="col-md-8 col-12">
            <div class="form-group">
                <label for="organization">سازمان</label>
                <select class="choices form-select"
                        name="organization" id="organization">
                    <optgroup label="Organization">
                        {% for organization in organizations %}
                            <option value="{{ organization.id }}">{{ organization }}</option>
                        {% endfor %}
                    </optgroup>
                </select>
            </div>
        </div>
        <label for="organization">محصولات</label>
        <br>
        {% for form in formset %}
            <div class="formset">
                <div class="col-md-11 col-12">
                    <div class="form-group">
                        <div class="col-md-12 mb-10">
                            <div class="input-group mb-10">
                                <label class="input-group-text"
                                       for="id_form-0-product">محصول</label>
                                {% render_field form.product class+="form-select" %}
                                <input type="number" class="form-control" name="form-0-price"
                                       min="0" id="id_form-0-price"
                                       placeholder="قیمت" required>
                                <input type="number" class="form-control" name="form-0-quantity"
                                       min="1" id="id_form-0-quantity"
                                       placeholder="تعداد" required>
                                <input type="number" class="form-control" name="form-0-discount"
                                       min="0" max="100" id="id_form-0-discount"
                                       placeholder="درصد تخفیف" required>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <button id="add-form" type="button" class="btn btn-secondary me-1 mb-1">محصول جدید</button>
        <button type="submit" class="btn btn-primary me-1 mb-1">ذخیره</button>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        let birdForm = document.querySelectorAll(".formset")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")
        let formNum = birdForm.length - 1
        addButton.addEventListener('click', addForm)

        function addForm(e) {
            e.preventDefault()
            let newForm = birdForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`, 'g')
            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`);
            container.insertBefore(newForm, addButton)
            totalForms.setAttribute('value', `${formNum + 1}`)
        }
    </script>
{% endblock %}

Quote/templates/QuoteList.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
    Quote List
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>لیست پیش فاکتور ها</h2>
    </div>
    <div class='text-white mt-lg-5' style="margin-left: 15%; margin-right: 15%;">
        <table class='table table-dark'>
            <thead>
            <tr>
                <th>#</th>
                <th>نام مشتری</th>
                <th>دستگاه ها</th>
                <th>فایل خروجی</th>
                <th>ارسال ایمیل به مخاطب</th>
            </tr>
            </thead>

            <tbody>
                {% for quote in object_list %}
                    <tr>
                        <th>{{forloop.counter}}</th>
                        <th>
                            <a href="#" style='text-decoration: none; color:white;'>{{quote.organ.name}}</a>
                        </th>
                        <th>{% for item in quote.quoteitem_set.all %}{{ item.product.product_name }},{% endfor %}</th>
                        <th>
                            {% if quote.pdf_file %}
                                <button class='btn btn-success'>
                                    <a href="{{quote.pdf_file.url}}" style='text-decoration: none; color: white;'>دانلود</a>
                                </button>
                            {% else %}
                                -
                            {% endif %}
                        </th>
                        <th>
                            <a href="{% url 'Quote:SendEmail' quote.pk %}" style='text-decoration: none; color:white;'>ارسال ایمیل</a>
                        </th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'base/Pagination.html' %}
{% endblock %}