CRM_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from Organization.views import OrganizationViewSetAPI
from .views import homepage

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    # path('login/', loginpage, name="login"),
    # path('admin/logout', admin.site.urls, name="logout"),
    path('login/', auth_views.LoginView.as_view(template_name='login_page.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', homepage, name="homepage"),
    path('Organization/', include('Organization.urls')),
    path('Product/', include('Product.urls')),
    path('Quote/', include('Quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Organization/urls.py
from django.urls import path
from .views import create_organ,organs_list,organ_detail,organ_update,show_follow_up,create_follow_up

app_name='Organization'
urlpatterns = [
    path('',create_organ.as_view(),name="CreateOrgan"),
    path('organslist/',organs_list.as_view(),name="OrgansList"),
    path('organdetail/<int:pk>',organ_detail.as_view(),name="OrganDetail"),
    path('organupdate/<int:pk>',organ_update.as_view(),name="OrganUpdate"),
    # path('showfollowup/<int:pk>', show_follow_up.as_view(), name="ShowFollowUp"),
    path('createfollowup/<int:pk>', create_follow_up.as_view(), name="CreateFollowUp"),
]

Product/urls.py
from django.urls import path
from .views import ProductList
app_name='Product'
urlpatterns = [
    path('productlist/', ProductList.as_view(), name='ProductList',),
]

Quote/urls.py
from django.urls import path
from .views import craete_quote,quote_list,send_email
app_name='Quote'
urlpatterns = [
    path('', craete_quote.as_view(), name='CreateQuote'),
    path('quotelist/', quote_list.as_view(), name='QuoteList'),
    path('sendemail/<int:pk>', send_email, name='SendEmail'),
]

auth/urls.py
from django.urls import path

urlpatterns = [

]

templates/base/FooterJS.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

templates/base/HeaderCss&JS.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">#}
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>#}

templates/base/Pagination.html
<div>
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">

            <li class="page-item">
                <a class="page-link" href="?page=1">اولین</a>
            </li>

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for num_page in paginator.page_range %}
                {% if page_obj.number == num_page %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{num_page}}">{{num_page}}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{num_page}}">{{num_page}}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}

            <li class="page-item">
                <a class="page-link" href="?page={{paginator.num_pages}}">آخرین</a>
            </li>

        </ul>
    </nav>
</div>

templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'base/HeaderCss&JS.html' %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="text-center">

{% include 'base/navbar.html' %}

<div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-12 mx-auto">
            <div class="jumbotron">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>
</div>

{% include 'base/FooterJS.html' %}

{% block scripts %}

{% endblock %}

</body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'homepage' %}">CRM</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "homepage" %}">خانه <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    محصولات
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'Product:ProductList' %}">لیست محصولات</a>
                </div>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    سازمان
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'Organization:CreateOrgan' %}">ایجاد سازمان جدید</a>
                    <a class="dropdown-item" href="{% url 'Organization:OrgansList' %}">لیست سازمان ها</a>
                </div>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    پیش فاکتور
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'Quote:CreateQuote' %}">ایجاد پیش فاکتور جدید</a>
                    <a class="dropdown-item" href="{% url 'Quote:QuoteList' %}">لیست پیش فاکتور ها</a>
                </div>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-right">
            {% if not user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'login' %}">ورود</a></li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ user.username }}</a>
                </li>
                <li><a class="nav-link" href="{% url 'logout' %}">خروج</a></li>
            {% endif %}
        </ul>
    </div>
</nav>