CRM_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from Organization.views import OrganizationViewSetAPI
from .views import homepage

router = DefaultRouter()
router.register('organization', OrganizationViewSetAPI)

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    # path('login/', loginpage, name="login"),
    # path('admin/logout', admin.site.urls, name="logout"),
    path('login/', auth_views.LoginView.as_view(template_name='login_page.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', homepage, name="homepage"),
    path('Organization/', include('Organization.urls')),
    path('Product/', include('Product.urls')),
    path('Quote/', include('Quote.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Organization/urls.py
from django.urls import path
from .views import create_organ,organs_list,organ_detail,organ_update,show_follow_up,create_follow_up

app_name='Organization'
urlpatterns = [
    path('',create_organ.as_view(),name="CreateOrgan"),
    path('organslist/',organs_list.as_view(),name="OrgansList"),
    path('organdetail/<int:pk>',organ_detail.as_view(),name="OrganDetail"),
    path('organupdate/<int:pk>',organ_update.as_view(),name="OrganUpdate"),
    # path('showfollowup/<int:pk>', show_follow_up.as_view(), name="ShowFollowUp"),
    path('createfollowup/<int:pk>', create_follow_up.as_view(), name="CreateFollowUp"),
]

Quote/urls.py
from django.urls import path
from .views import craete_quote,quote_list,send_email
app_name='Quote'
urlpatterns = [
    path('', craete_quote.as_view(), name='CreateQuote'),
    path('quotelist/', quote_list.as_view(), name='QuoteList'),
    path('sendemail/<int:pk>', send_email, name='SendEmail'),
]

auth/urls.py
from django.urls import path

urlpatterns = [

]

Organization/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_jalali.db import models as jdate
from Product.models import Product

phone_regex = RegexValidator(
    regex='^(\+98|0)?\d{1,2}\d{1,8}$',
    message=_("تلفن وارد شده معتبر نیست"),
    code='invalid_phone',
)


# Create your models here.

class OrganizationProduct(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("محصولات تولیدی"), )

    class Meta():
        verbose_name = _("محصول تولیدی")
        verbose_name_plural = _("محصولات تولیدی")

    def __str__(self):
        return self.name

    def get_sug_product(self):
        return [product for product in self.product_set.all()]



class State(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("استان"), unique=True, )

    class Meta():
        verbose_name = _("استان")
        verbose_name_plural = _("استان ها")

    def __str__(self):
        return self.name


class Organization(models.Model):
    state = models.ForeignKey(State, verbose_name=_("استان"), on_delete=models.PROTECT, default=None, )
    name = models.CharField(max_length=200, verbose_name=_("نام سازمان"), unique=True, )
    phone = models.CharField(max_length=11, verbose_name=_("تلفن"), validators=[phone_regex], )
    workers_qty = models.PositiveIntegerField(default=1, verbose_name=_("تعداد کارگران"), )
    organ_product = models.ManyToManyField('OrganizationProduct', verbose_name=_("محصولات تولیدی"), )
    full_name_owner = models.CharField(max_length=200, verbose_name=_("نام و نام خانوادگی مخاطب"), default=None, )
    phone_owner = models.CharField(max_length=11, verbose_name=_("تلفن مخاطب"), validators=[phone_regex], )
    email_owner = models.EmailField(verbose_name=_("ایمیل مخاطب"), blank=True, )
    created_at = jdate.jDateTimeField(verbose_name=_("تاریخ ثبت"), auto_now_add=True, )
    user_creator = models.ForeignKey(get_user_model(), verbose_name=_("کاربر ایجاد کننده"), on_delete=models.PROTECT)

    class Meta():
        unique_together = ['name','user_creator' ]
        verbose_name = _("سازمان")
        verbose_name_plural = _("سازمان ها")

    def __str__(self):
        return self.name

    def get_organ_product(self):
        return [product.name for product in self.organ_product.all()]

    def get_sug_product(self):
        p = list()
        for product in self.organ_product.all():
            for l in product.get_sug_product():
                p.append(l.product_name)
        p = set(p)
        return list(p)


class FollowUp(models.Model):
    description = models.TextField(verbose_name=_('گزارش کار'))
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, verbose_name=_('نام سازمان'))
    user_creator = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name=_('کاربر ایجاد کننده'))
    created_at = jdate.jDateTimeField(auto_now_add=True, verbose_name=_('تاریخ ثبت'))

    class Meta():
        verbose_name = _("پیگیری")
        verbose_name_plural = _("پیگیری ها")

Organization/forms.py
from django import forms
from . import models


class OrganForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = [
            'state',
            'name',
            'phone',
            'workers_qty',
            'organ_product',
            'full_name_owner',
            'phone_owner',
            'email_owner',
        ]


class OrganProductForm(forms.ModelForm):
    class Meta:
        model = models.OrganizationProduct
        fields = [
            'name',
        ]


class FollowUpForm(forms.ModelForm):
    class Meta:
        model = models.FollowUp
        fields = [
            'description',
        ]

Organization/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from rest_framework_simplejwt.authentication import JWTAuthentication

from . import models, forms, serializers

# Create your views here.
from django.views.generic import CreateView, ListView, DetailView, UpdateView, FormView


class create_organ(LoginRequiredMixin, CreateView):
    model = models.Organization
    template_name = 'CreateOrgan.html'
    form_class = forms.OrganForm
    success_url = reverse_lazy("Organization:OrgansList")

    def form_valid(self, form):
        form.instance.user_creator = self.request.user
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.info(self.request, form.errors)
        return super().form_invalid(form)


class organs_list(LoginRequiredMixin, ListView):
    model = models.Organization
    template_name = 'OrganList.html'
    paginate_by = 4


class organ_detail(LoginRequiredMixin, DetailView):
    model = models.Organization
    template_name = 'OrganDetail.html'

    def get_queryset(self):
        organization = models.Organization.objects.filter(pk=self.kwargs['pk'], user_creator=self.request.user)
        return organization


class organ_update(LoginRequiredMixin, UpdateView):
    model = models.Organization
    template_name = 'EditOrgan.html'
    form_class = forms.OrganForm

    def get_queryset(self):
        organization = models.Organization.objects.filter(pk=self.kwargs['pk'], user_creator=self.request.user)
        return organization

    def get_success_url(self):
        return reverse_lazy('Organization:OrganDetail', kwargs={'pk': self.object.pk})


class show_follow_up(LoginRequiredMixin, CreateView):
    pass


@method_decorator(csrf_exempt, name='dispatch')
class create_follow_up(LoginRequiredMixin, CreateView):
    model = models.FollowUp
    fields = [
        'description'
    ]
    template_name = 'CreateFollowUp.html'

    def form_invalid(self, form):
        return JsonResponse(data={
            'success': 'False',
        }, status=400)

    def form_valid(self, form):
        form.save(commit=False).user_creator = self.request.user
        form.save(commit=False).organization = models.Organization.objects.get(pk=self.kwargs['pk'])
        form.save()
        return JsonResponse(data={
            'success': 'True',
        }, status=200)

    def get_context_data(self, **kwargs):
        context = {
            'organization': models.Organization.objects.get(pk=self.kwargs['pk']),
        }
        return context


class OrganizationViewSetAPI(ModelViewSet):
    serializer_class = serializers.OrganizationSerializer
    permission_classes = [IsAuthenticated]
    authentication_classes = [JWTAuthentication]
    queryset = models.Organization.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(creator=self.request.user)

    def perform_create(self, serializer):
        serializer.save(creator=self.request.user)

Organization/templates/CreateFollowUp.html
{% extends "base/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    Create Follow Up
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>ثبت پیگیری</h2>
    </div>
    <form method="post" id="formsubmit">
        {% csrf_token %}
        <div class="form-group">
            <label for="description"></label>
            <textarea id="description" name="description" rows="5"
                      placeholder="{{ form.description.label }}"></textarea>
        </div>

        <button type="submit" class="btn btn-primary" id="btnsubmit">ذخیره</button>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#btnsubmit').on('click', function (event) {
                var description = $('#description').val();

                $.ajax({
                    method: 'POST',
                    url: '{% url 'Organization:CreateFollowUp' organization.pk %}',
                    data: {
                        description: description
                    },
                    success: function (response) {
                        alert('با موفقیت ذخیره شد.');
                    },
                    error: function (response) {
                        alert('اطلاعات وارد شده صحیح نیست.');
                    },

                })
            });
        });
    </script>
{% endblock %}

Organization/templates/CreateOrgan.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
Create Organization
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>ایجاد سازمان جدید</h2>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="state">استان</label>
            <select class="form-control" id="state" name="state">
                {% for item in form.fields.state.queryset %}
                    <option value="{{ forloop.counter }}">{{ item }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="name">نام سازمان</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="نام سازمان">
        </div>
        <div class="form-group">
            <label for="phone">تلفن</label>
            <input type="text" class="form-control" maxlength="11" id="phone" name="phone" placeholder="تلفن">
        </div>
        <div class="form-group">
            <label for="workers_qty">تعداد کارگران</label>
            <input type="number" min="0" class="form-control" id="workers_qty" name="workers_qty">
        </div>
        <div class="form-group">
            <label for="organ_product" class="form-label">محصولات تولیدی</label>
            <select id='organ_product' name='organ_product' class="custom-select" multiple>
                {% for item in form.fields.organ_product.queryset %}
                    {% if item %}
                        <option value="{{ forloop.counter }}">{{ item }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="full_name_owner">نام و نام خانوادگی مخاطب</label>
            <input type="text" class="form-control" id="full_name_owner" name="full_name_owner"
                   placeholder="نام و نام خانوادگی مخاطب">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="phone_owner">تلفن مخاطب</label>
                <input type="text" class="form-control" maxlength="11" id="phone_owner" name="phone_owner"
                       placeholder="تلفن مخاطب">
            </div>
            <div class="form-group col-md-6">
                <label for="email_owner">ایمیل مخاطب</label>
                <input type="email" class="form-control" id="email_owner" name="email_owner" placeholder="ایمیل مخاطب">
            </div>
        </div>

        <button type="submit" class="btn btn-primary">ذخیره</button>
    </form>
{% endblock %}

Organization/templates/EditOrgan.html
{% extends "base/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Update Organization
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>ویرایش {{ form.name.value }}</h2>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="state">استان</label>
            {% render_field form.state class+="form-control" type="select" %}
        </div>
        <div class="form-group">
            <label for="name">نام سازمان</label>
            {% render_field form.name class+="form-control" type="text" %}
        </div>
        <div class="form-group">
            <label for="phone">تلفن</label>
            {% render_field form.phone class+="form-control" type="text" %}
        </div>
        <div class="form-group">
            <label for="workers_qty">تعداد کارگران</label>
            {% render_field form.workers_qty class+="form-control" type="number" min="0" %}
        </div>
        <div class="form-group">
            <label for="organ_product" class="form-label">محصولات تولیدی</label>
            {% render_field form.organ_product class+="form-control" type="select" %}
        </div>
        <div class="form-group">
            <label for="full_name_owner">نام و نام خانوادگی مخاطب</label>
            {% render_field form.full_name_owner class+="form-control" type="text" %}
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="phone_owner">تلفن مخاطب</label>
                {% render_field form.phone_owner class+="form-control" type="text" %}
            </div>
            <div class="form-group col-md-6">
                <label for="email_owner">ایمیل مخاطب</label>
                {% render_field form.email_owner class+="form-control" type="email" %}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">ذخیره</button>
    </form>
{% endblock %}

Organization/templates/OrganDetail.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
    Organization Detail
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>{{ object.name }}</h2>
    </div>
    <div>
        <a href="{% url 'Organization:OrgansList' %}" class="btn btn-primary">بازگشت</a>
        <a href="{% url 'Quote:CreateQuote' %}" class="btn btn-primary">پیش فاکتور</a>
        <a href="{% url 'Organization:OrganUpdate' object.pk %}" class="btn btn-primary">ویرایش</a>
    </div>
    <div class="card-body">
        استان : {{ object.state }}
        <br>
        تلفن : {{ object.phone }}
        <br>
        تاریخ ثبت : {{ object.created_at.date }}
        <br>
        تعداد کارگر : {{ object.workers_qty }}
        <br>
        ثبت توسط : {{ object.user_creator.first_name }} {{ object.user_creator.last_name }}
        <br>
        محصولات تولیدی : {% for product in object.get_organ_product %} ,{{ product }}{% endfor %}
        <br>
        محصولات پیشنهادی : {% for product in object.get_sug_product %} ,{{ product }} {% endfor %}
    </div>
    <div class="text-center">
        <h2>اطلاعات مخاطب</h2>
    </div>
    <div class="card-body">
        نام مخاطب : {{ object.full_name_owner }}
        <br>
        تلفن مخاطب : {{ object.phone_owner }}
        <br>
    </div>
    <div class="text-center">
        <h2>تاریخچه پیگیری</h2>
    </div>
    <div class='text-white mt-lg-5' style="margin-left: 15%; margin-right: 15%;">
        <table class='table table-dark'>
            <thead>
            <tr>
                <th>#</th>
                <th>کاربر</th>
                <th>تاریخ</th>
                <th>گزارش</th>
            </tr>
            </thead>

            <tbody>
            {% for followup in object_list %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <th>
                        <a href="#" style='text-decoration: none; color:white;'>{{ followup.product_name }}</a>
                    </th>
                    <th>{{ followup.price }}</th>
                    <th>
                        {{ followup.price }}
                    </th>
                    <th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'base/Pagination.html' %}
{% endblock %}

Organization/templates/OrganList.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
    Create Product
{% endblock %}

{% block content %}
    <div class="text-center">
        <h2>لیست سازمان ها</h2>
    </div>
    <div class='text-white mt-lg-5' style="margin-left: 15%; margin-right: 15%;">
        <table class='table table-dark'>
            <thead>
            <tr>
                <th>#</th>
                <th>نام سازمان</th>
                <th>ثبت کننده</th>
                <th>مخاطب</th>
                <th>عملیات</th>
            </tr>
            </thead>

            <tbody>
            {% for organ in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'Organization:OrganDetail' organ.pk %}"
                           style='text-decoration: none; color:white;'>{{ organ.name }}</a>
                    </td>
                    <td>{{ organ.user_creator }}</td>
                    <td>
                        {{ organ.full_name_owner }}
                    </td>
                    <td>
                        <a href="{% url 'Organization:CreateFollowUp' organ.pk %}  ">ثبت پیگیری</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include 'base/Pagination.html' %}
{% endblock %}